### PR TITLE
Add functionality to use navigator.sendBeacon

### LINKED ISSUE #16: Using Navigator.sendBeacon for sending data
The current implementation of the `plausible-tracker` uses the common [XMLHttpRequest](https://github.com/plausible/plausible-tracker/blob/master/src/lib/request.ts#L61) for submitting analytics data. Yet with advancements in browser engines, a more specialized submit-method is available via the `navigator`, called `sendBeacon`, purpose-build for analytics requests.

[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon)

## Detailed Description
On platforms that support both a `navigator` as well the `sendBeacon` function, it would make sense to adopt this API for submitting analytics-data by progressively enhancing the request-module of plausible-tracker. A short summary of the advantages compared to `XMLHttpRequest` (taken from MDN):

- The data is sent reliably
- It's sent asynchronously
- It doesn't impact the loading of the next page

B/c the submit-event gets queue and reliably sent by browser, using `sendBeacon` should have a zero-impact on transmitting analytics data while also guaranteeing that the data gets sent, eventually. 

Using `navigator.sendBeach` would therefore ready plausible-tracker for best usage in modern browsers.

## Context
Benefits explained before.

## Possible Implementation
As a first draft, a simple if/else check for compat should be sufficient to determine the correct submit-function to use.

### PR DESCRIPTION
**Pull request by A5rocks**
## Description
Use a better method of analytics posting.

## Related Issue
Fixes #16.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Maronato/plausible-tracker/blob/master/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

I think a followup to this would be using `navigator.sendBeacon` unless `callback` is passed. I would be OK with adding that into this.

### CODE REVIEW

**Comment by A5rocks** [comment]
@ukutaht Hello! Just making sure you've seen this PR. Do you have any opinions for whether `navigator.sendBeacon` should be the default (as mentioned in #16 or at the end of my PR explanation)?

Additionally you need to allow (approve?) the workflow to run :P

**Comment by ukutaht** [comment]
Hi!

We have considered it but have decided against using sendBeacon at this time. Sorry :/

**Comment by A5rocks** [comment]
Alright, thanks.

**Comment by kotx** [comment]
> We have considered it but have decided against using sendBeacon at this time. Sorry :/

@ukutaht Are there any reasons for this? Just curious :)

**Comment by ukutaht** [comment]
The main reason is that we don't currently have team capacity to evaluate this change properly. We'd need to evaluate this approach before choosing to adopt it.

Adding `sendBeacon` with progressive enhancement will certainly do the following:
1. Increases JS payload size
2. Make the script more complicated
  2.1  Harder to use and understand
  2.2. More opportunities for errors
  2.3 Harder to maintain over time

In order to accept long-term maintenance of this complexity, strong arguments must be made. The main pieces of data I'm looking for are:
1. How much bigger does the JS payload get
2. What's the % increase/decrease in reliability when using sendBeacon?
  2.1 Need to test with different audiences as adblockers set `navigator.sendBeacon = function() {}`

These two numbers should give us good enough understanding to make a decision.

**Comment by LewisTehMinerz** [comment]
As someone who also desires this feature it's a little disappointing to see this closed and I'm sure other people are too.

> 1. Increases JS payload size
> 2. Make the script more complicated
> 2.1 Harder to use and understand
> 2.2. More opportunities for errors
> 2.3 Harder to maintain over time

Whilst I understand these points being a concern, the PR itself is about 5 extra lines of code, of which the majority is just adding the new `useSendBeacon` parameter. I wouldn't consider this extra complexity, personally, just extra flexibility to those who desire it, especially since the parameter is optional. Also, the error opportunities would most likely be the fault of the browser's implementation of sendBeacon, less so any change this PR creates. Maintenance-wise, with the way it's implemented, it shouldn't really need any.

> 1. How much bigger does the JS payload get

Using `yarn build:module`, the built `request.js` file increases from 3,319 bytes to 3,710 bytes (~11.7%). When minified, I imagine this will barely be a dent in the overall bundle size. I'm aware Plausible is trying to be as lightweight as possible, but I believe that missing out on this feature for a (relatively) small increase in size.

> 2. What's the % increase/decrease in reliability when using sendBeacon?
> 2.1 Need to test with different audiences as adblockers set navigator.sendBeacon = function() {}

The reliability would actually be increased. I don't have percents for you, but considering sendBeacon's purpose it would pretty much guarantee an event would be sent even after they navigate away from the page. It wouldn't be any less reliable than the current method. Regarding adblocking, I've experienced Plausible being adblocked on a few that I've tried so it's not much of a concern here if they no-op sendBeacon.

**Comment by carlmjohnson** [comment]
FWIW, I'm evaluating Plausible for my company and using sendBeacon is one of our requirements. I'm just going to rewrite the JS myself to make it work. The flipside of Plausible's JS being 3KB is you can rewrite it yourself in an afternoon.

**Comment by A5rocks** [comment]
If you do end up rewriting it and decide it's good enough to share, mind doing so? We were going to use a rewritten version but decided that would be too much work! (I still have our untested version on disk... heh. It's for some time in the future, I suppose.)

**Comment by carlmjohnson** [comment]
@A5rocks https://github.com/spotlightpa/poor-richard/commit/39585915752a0b3338c3d442b440c7f029780156

**Pull request closed without merging**
